apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - name: my-container
    image: nginx:latest  # Example container image (can be changed)
    ports:
    - containerPort: 80  # Port exposed by the container
